### PR TITLE
enhancement: build also in dockerfile - transparent build different platforms

### PR DESCRIPTION
**Pull request by mabunixda**
## Summary

Also run the actual build process of the exporter within the dockerfile - so this is portable to run it also on e.g. raspis with this dockerfile definition

## Checklist

- enhancement 
- no documentation update needed

### CODE REVIEW

**Comment by ccremer** [comment]
Hi @mabunixda 
Thanks for your interest in the project and making a PR.

Did you know that crossbuild is already happening with [Goreleaser](https://github.com/ccremer/fronius-exporter/blob/master/.goreleaser.yml)? Inside that config file you will see which OS and arch is enabled and which Docker images. Right now, it's for linux/amd64, linux/arm64/v8 and linux/arm/v7. This is done with Docker manifest, so when pulling `latest` and [other tags](https://github.com/ccremer/fronius-exporter/pkgs/container/fronius-exporter), your docker client should automatically select the version for our OS and arch. The ARM images _should_ cover your case for a raspi.

In case a particular arch is missing, please let me know.

**Comment by mabunixda** [comment]
Ok i missed that - but how can this be done locally ?

**Comment by ccremer** [comment]
There's no direct support for crossbuilding locally. However you have some options to figure out.

You can either: build locally with goreleaser or manually

With Goreleaser:
```bash
export GOOS=linux
export GOARCH=arm64
export IMAGE_REPOSITORY=ccremer/fronius-exporter
goreleaser build --snapshot --rm-dist --single-target
```
(I don't know if `goreleaser build` also builds the docker image though and not just the binary. Otherwise use `goreleaser release --snapshot --skip-sign`)

```bash
export GOOS=linux
export GOARCH=arm64
make build
# you now have a binary with arm64 arch

docker buildx build --platform ... .
```
I didn't test neither approach, but hopefully it helps you.

**Comment by ccremer** [comment]
Hi @mabunixda 
Did that help you? If yes, we could consider adding some lines to the README at least.

**Pull request closed without merging**
